services:
  ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./.hf_cache:/tmp/.cache/huggingface
    env_file:
      - .env
    environment:
      - HF_HOME=/tmp/.cache/huggingface
